# Komplizierte Technologien Docker Compose (https://github.com/dimasch/magento2-docker-compose)
# Version 2.1.0

app:
  image: mageinferno/magento2-nginx:1.9.9-1
  dns: 8.8.8.8
  ports:
    - "80:80"
  links:
    - php-fpm
    - db
  volumes_from:
    - appdata
  environment:
    - APP_MAGE_MODE=developer
#   - VIRTUAL_HOST=m2.docker

appdata:
  image: tianon/true
  volumes:
    - ./src:/src
    - ~/.composer:/root/.composer
    - ~/.ssh:/root/.ssh

"php-fpm":
  image: komplizierte/docker-magento2-php
  dns: 8.8.8.8
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - APP_MAGE_MODE=developer
    - PHP_MEMORY_LIMIT=4G

db:
  image: mariadb:10.1.10
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

setup:
  image: komplizierte/docker-magento2-php
  command: /usr/local/bin/mage-setup
  dns: 8.8.8.8
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento2
    - M2SETUP_DB_USER=magento2
    - M2SETUP_DB_PASSWORD=magento2
    - M2SETUP_BASE_URL=http://m2.docker/
    - M2SETUP_ADMIN_FIRSTNAME=Admin
    - M2SETUP_ADMIN_LASTNAME=User
    - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
    - M2SETUP_ADMIN_USER=magento2
    - M2SETUP_ADMIN_PASSWORD=magento2
    - M2SETUP_VERSION=2.0.2
    - M2SETUP_USE_ARCHIVE=false
    - M2SETUP_USE_SAMPLE_DATA=true
    - M2SETUP_PROJECT_URL=https://github.com/magento/magento2-community-edition.git
